/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    'product-categories': ProductCategory;
    'product-collections': ProductCollection;
    products: Product;
    'product-variants': ProductVariant;
    orders: Order;
    discounts: Discount;
    reviews: Review;
    carts: Cart;
    'inventory-levels': InventoryLevel;
    'stock-locations': StockLocation;
    'stock-movements': StockMovement;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    'product-collections': ProductCollectionsSelect<false> | ProductCollectionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    discounts: DiscountsSelect<false> | DiscountsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'inventory-levels': InventoryLevelsSelect<false> | InventoryLevelsSelect<true>;
    'stock-locations': StockLocationsSelect<false> | StockLocationsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role: 'super_admin' | 'admin' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  hasAccount?: boolean | null;
  addresses?:
    | {
        firstName?: string | null;
        lastName?: string | null;
        company?: string | null;
        address1: string;
        address2?: string | null;
        city: string;
        /**
         * State / Province / County
         */
        province?: string | null;
        postalCode: string;
        /**
         * ISO 3166-1 alpha-2. e.g. "KE"
         */
        countryCode: string;
        phone?: string | null;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional ID from an external CRM or loyalty system.
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  /**
   * URL-safe identifier. e.g. "eau-de-parfum"
   */
  handle: string;
  description?: string | null;
  thumbnail?: (number | null) | Media;
  /**
   * Leave empty for a top-level category.
   */
  parent?: (number | null) | ProductCategory;
  /**
   * Controls display order. Lower numbers appear first.
   */
  rank?: number | null;
  isActive?: boolean | null;
  /**
   * Internal categories are hidden from the storefront.
   */
  isInternal?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-collections".
 */
export interface ProductCollection {
  id: number;
  title: string;
  /**
   * URL-safe identifier. e.g. "summer-edit"
   */
  handle: string;
  description?: string | null;
  thumbnail?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Display name. e.g. "Oud Noir"
   */
  title: string;
  /**
   * URL slug. e.g. "oud-noir"
   */
  handle: string;
  /**
   * Short tagline shown under the product title.
   */
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail: number | Media;
  /**
   * Additional product images shown in the gallery.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * The perfume house or brand. e.g. "Maison Magnetic"
   */
  brand?: string | null;
  fragranceType?: ('edp' | 'edt' | 'edc' | 'parfum' | 'eau-fraiche' | 'body-mist' | 'solid') | null;
  gender?: ('unisex' | 'men' | 'women') | null;
  fragranceFamily?:
    | ('floral' | 'oriental' | 'woody' | 'fresh' | 'aquatic' | 'gourmand' | 'fougere' | 'chypre' | 'musk' | 'oud')[]
    | null;
  scentNotes?: {
    /**
     * Comma-separated. e.g. "Bergamot, Pink Pepper"
     */
    top?: string | null;
    /**
     * Comma-separated. e.g. "Rose, Jasmine, Oud"
     */
    heart?: string | null;
    /**
     * Comma-separated. e.g. "Sandalwood, Amber, Musk"
     */
    base?: string | null;
  };
  longevity?: ('very-weak' | 'weak' | 'moderate' | 'long-lasting' | 'very-long-lasting') | null;
  /**
   * How far the scent projects from the wearer.
   */
  sillage?: ('intimate' | 'soft' | 'moderate' | 'strong' | 'enormous') | null;
  category?: (number | null) | ProductCategory;
  collection?: (number | null) | ProductCollection;
  status: 'draft' | 'published' | 'archived';
  /**
   * Allow discount codes to apply to this product.
   */
  discountable?: boolean | null;
  /**
   * Used for search and filtering.
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional ID from an external system (ERP, 3PL).
   */
  externalId?: string | null;
  /**
   * Overrides for search engine listings.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  /**
   * Variant display name. e.g. "50ml" or "Travel Size – 10ml"
   */
  title: string;
  product: number | Product;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Volume in ml. e.g. 30, 50, 100
   */
  volume?: number | null;
  concentration?: ('edp' | 'edt' | 'edc' | 'parfum' | 'eau-fraiche') | null;
  /**
   * Price in smallest currency unit (e.g. 5000 = $50.00).
   */
  price: number;
  /**
   * Pre-sale price to show a "was/now" comparison.
   */
  originalPrice?: number | null;
  /**
   * Stock Keeping Unit. e.g. "ON-EDP-50"
   */
  sku?: string | null;
  barcode?: string | null;
  /**
   * European Article Number (EAN-13).
   */
  ean?: string | null;
  /**
   * Universal Product Code (UPC-A).
   */
  upc?: string | null;
  /**
   * Track stock via Inventory Levels. Disable for made-to-order or digital items.
   */
  manageInventory?: boolean | null;
  /**
   * Allow purchases even when all locations are out of stock.
   */
  allowBackorder?: boolean | null;
  /**
   * Weight in grams.
   */
  weight?: number | null;
  /**
   * Height in mm.
   */
  height?: number | null;
  /**
   * Width in mm.
   */
  width?: number | null;
  /**
   * Length in mm.
   */
  length?: number | null;
  /**
   * ISO 3166-1 alpha-2 country code. e.g. "FR"
   */
  originCountry?: string | null;
  /**
   * HS tariff code for international shipping.
   */
  hsCode?: string | null;
  /**
   * Display order in the variant selector. Lower = first.
   */
  variantRank?: number | null;
  /**
   * Optional ID from an external system (ERP, 3PL).
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Human-readable order ID. e.g. "MC-00123"
   */
  orderNumber: string;
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded' | 'requires_action';
  paymentStatus: 'awaiting' | 'captured' | 'partially_refunded' | 'refunded' | 'cancelled' | 'not_paid';
  customer?: (number | null) | Customer;
  /**
   * Always stored — covers guest checkouts too.
   */
  email: string;
  items: {
    variant: number | ProductVariant;
    title: string;
    productTitle: string;
    thumbnail?: (number | null) | Media;
    quantity: number;
    unitPrice: number;
    subtotal: number;
    sku?: string | null;
    id?: string | null;
  }[];
  shippingAddress: {
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    address1: string;
    address2?: string | null;
    city: string;
    province?: string | null;
    postalCode: string;
    countryCode: string;
    phone?: string | null;
  };
  billingAddress: {
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    address1: string;
    address2?: string | null;
    city: string;
    province?: string | null;
    postalCode: string;
    countryCode: string;
    phone?: string | null;
  };
  /**
   * ISO 4217 currency code. e.g. "kes", "usd"
   */
  currency: string;
  /**
   * Sum of line item subtotals before discounts and shipping.
   */
  subtotal: number;
  discountTotal?: number | null;
  shippingTotal?: number | null;
  taxTotal?: number | null;
  total: number;
  /**
   * e.g. "stripe", "mpesa", "paystack"
   */
  paymentProvider?: string | null;
  /**
   * Provider-side transaction/payment intent ID.
   */
  paymentId?: string | null;
  /**
   * e.g. "Standard Delivery", "Express"
   */
  shippingMethod?: string | null;
  trackingNumber?: string | null;
  trackingUrl?: string | null;
  shippedAt?: string | null;
  deliveredAt?: string | null;
  /**
   * Note left by the customer at checkout.
   */
  customerNote?: string | null;
  /**
   * Internal note visible to admins only.
   */
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts".
 */
export interface Discount {
  id: number;
  /**
   * Coupon code. e.g. "SUMMER20"
   */
  code: string;
  type: 'percentage' | 'fixed' | 'free_shipping';
  /**
   * For percentage: 0–100. For fixed: amount in smallest currency unit.
   */
  value?: number | null;
  /**
   * Minimum order total (in smallest currency unit).
   */
  minimumAmount?: number | null;
  usageLimit?: number | null;
  usageCount?: number | null;
  isOncePerCustomer?: boolean | null;
  startsAt?: string | null;
  endsAt?: string | null;
  isActive?: boolean | null;
  /**
   * Leave empty to apply to all products.
   */
  applicableProducts?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  customer?: (number | null) | Customer;
  order?: (number | null) | Order;
  rating: number;
  headline: string;
  body: string;
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  status: 'active' | 'completed' | 'abandoned';
  customer?: (number | null) | Customer;
  email?: string | null;
  items?:
    | {
        variant: number | ProductVariant;
        quantity: number;
        unitPrice: number;
        variantTitle?: string | null;
        productTitle?: string | null;
        thumbnail?: (number | null) | Media;
        sku?: string | null;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    countryCode?: string | null;
    phone?: string | null;
  };
  billingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    countryCode?: string | null;
    phone?: string | null;
  };
  sameAsShipping?: boolean | null;
  shippingMethod?: {
    id?: string | null;
    label?: string | null;
    price?: number | null;
    estimatedDays?: number | null;
  };
  discount?: (number | null) | Discount;
  discountTotal?: number | null;
  currency: string;
  subtotal?: number | null;
  shippingTotal?: number | null;
  taxTotal?: number | null;
  total?: number | null;
  /**
   * e.g. "stripe", "mpesa", "paystack"
   */
  paymentProvider?: string | null;
  paymentIntentId?: string | null;
  cartToken?: string | null;
  /**
   * Populated once the cart converts to an order.
   */
  completedOrderId?: (number | null) | Order;
  customerNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-levels".
 */
export interface InventoryLevel {
  id: number;
  variant: number | ProductVariant;
  location: number | StockLocation;
  stockedQuantity: number;
  /**
   * Managed automatically. Units held by active carts.
   */
  reservedQuantity: number;
  /**
   * Computed automatically. stockedQuantity − reservedQuantity.
   */
  availableQuantity?: number | null;
  lowStockThreshold?: number | null;
  /**
   * Trigger a restock when stock falls to this level.
   */
  reorderPoint?: number | null;
  /**
   * How many units to reorder when reorderPoint is hit.
   */
  reorderQuantity?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-locations".
 */
export interface StockLocation {
  id: number;
  /**
   * e.g. "Nairobi Warehouse", "Westgate Pop-Up"
   */
  name: string;
  type?: ('warehouse' | 'store' | '3pl') | null;
  address?: {
    address1?: string | null;
    city?: string | null;
    countryCode?: string | null;
  };
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: number;
  variant: number | ProductVariant;
  location: number | StockLocation;
  type:
    | 'restock'
    | 'sale'
    | 'return'
    | 'adjustment'
    | 'damage'
    | 'transfer_out'
    | 'transfer_in'
    | 'reserved'
    | 'reservation_released';
  /**
   * Use positive numbers for stock in, negative for stock out.
   */
  quantity: number;
  quantityAfter: number;
  /**
   * e.g. "PO-2025-041", "Order MC-00123", "Damaged in transit"
   */
  reason?: string | null;
  order?: (number | null) | Order;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'product-collections';
        value: number | ProductCollection;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'discounts';
        value: number | Discount;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'inventory-levels';
        value: number | InventoryLevel;
      } | null)
    | ({
        relationTo: 'stock-locations';
        value: number | StockLocation;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: number | StockMovement;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  hasAccount?: T;
  addresses?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        company?: T;
        address1?: T;
        address2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        countryCode?: T;
        phone?: T;
        isDefault?: T;
        id?: T;
      };
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  handle?: T;
  description?: T;
  thumbnail?: T;
  parent?: T;
  rank?: T;
  isActive?: T;
  isInternal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-collections_select".
 */
export interface ProductCollectionsSelect<T extends boolean = true> {
  title?: T;
  handle?: T;
  description?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  handle?: T;
  subtitle?: T;
  description?: T;
  thumbnail?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  brand?: T;
  fragranceType?: T;
  gender?: T;
  fragranceFamily?: T;
  scentNotes?:
    | T
    | {
        top?: T;
        heart?: T;
        base?: T;
      };
  longevity?: T;
  sillage?: T;
  category?: T;
  collection?: T;
  status?: T;
  discountable?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  externalId?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  volume?: T;
  concentration?: T;
  price?: T;
  originalPrice?: T;
  sku?: T;
  barcode?: T;
  ean?: T;
  upc?: T;
  manageInventory?: T;
  allowBackorder?: T;
  weight?: T;
  height?: T;
  width?: T;
  length?: T;
  originCountry?: T;
  hsCode?: T;
  variantRank?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  paymentStatus?: T;
  customer?: T;
  email?: T;
  items?:
    | T
    | {
        variant?: T;
        title?: T;
        productTitle?: T;
        thumbnail?: T;
        quantity?: T;
        unitPrice?: T;
        subtotal?: T;
        sku?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        company?: T;
        address1?: T;
        address2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        countryCode?: T;
        phone?: T;
      };
  billingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        company?: T;
        address1?: T;
        address2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        countryCode?: T;
        phone?: T;
      };
  currency?: T;
  subtotal?: T;
  discountTotal?: T;
  shippingTotal?: T;
  taxTotal?: T;
  total?: T;
  paymentProvider?: T;
  paymentId?: T;
  shippingMethod?: T;
  trackingNumber?: T;
  trackingUrl?: T;
  shippedAt?: T;
  deliveredAt?: T;
  customerNote?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts_select".
 */
export interface DiscountsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  minimumAmount?: T;
  usageLimit?: T;
  usageCount?: T;
  isOncePerCustomer?: T;
  startsAt?: T;
  endsAt?: T;
  isActive?: T;
  applicableProducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  customer?: T;
  order?: T;
  rating?: T;
  headline?: T;
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  status?: T;
  customer?: T;
  email?: T;
  items?:
    | T
    | {
        variant?: T;
        quantity?: T;
        unitPrice?: T;
        variantTitle?: T;
        productTitle?: T;
        thumbnail?: T;
        sku?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        address1?: T;
        address2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        countryCode?: T;
        phone?: T;
      };
  billingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        address1?: T;
        address2?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        countryCode?: T;
        phone?: T;
      };
  sameAsShipping?: T;
  shippingMethod?:
    | T
    | {
        id?: T;
        label?: T;
        price?: T;
        estimatedDays?: T;
      };
  discount?: T;
  discountTotal?: T;
  currency?: T;
  subtotal?: T;
  shippingTotal?: T;
  taxTotal?: T;
  total?: T;
  paymentProvider?: T;
  paymentIntentId?: T;
  cartToken?: T;
  completedOrderId?: T;
  customerNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-levels_select".
 */
export interface InventoryLevelsSelect<T extends boolean = true> {
  variant?: T;
  location?: T;
  stockedQuantity?: T;
  reservedQuantity?: T;
  availableQuantity?: T;
  lowStockThreshold?: T;
  reorderPoint?: T;
  reorderQuantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-locations_select".
 */
export interface StockLocationsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  address?:
    | T
    | {
        address1?: T;
        city?: T;
        countryCode?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  variant?: T;
  location?: T;
  type?: T;
  quantity?: T;
  quantityAfter?: T;
  reason?: T;
  order?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}